### ISSUE TITLE
[Bug/Question] Code blocks not rendered with mike, but with plain mkdocs

### ISSUE THREAD

**Issue by iwilltry42** [jimporter/mike#105]
Hi there :wave: 
We've been using mike for versioned docs on https://k3d.io for quite some time already without issues.
However, just recently we discovered, that code blocks stopped being rendered.
See https://k3d.io/v5.4.1/usage/configfile/#all-options-example & https://k3d.io/v5.4.2/usage/configfile/#all-options-example

Debugging this locally showed, that `mkdocs serve` does it well, while `mike serve` somehow doesn't do it.

It looks super weird to me, but I cannot figure out the issue here.

Do you have any idea?

Thanks in advance!

**Comment by iwilltry42** [comment]
OK, I'm super confused now.... next version built successfully :thinking: 
See https://k3d.io/v5.4.3/usage/configfile/
So maybe it was just a hiccup. Feel free to close, if it's not interesting :+1:

**Comment by jimporter** [comment]
I'd be surprised if this were an issue in mike, since it doesn't actually do anything with the Markdown files themselves.

My guess is that during CI, a bad combination of dependencies got installed that resulted in this issue. You'd then see that bad result via `mike serve` locally, since all that command does is start a dev server that serves the pages from the head of the `gh-pages` branch (`mkdocs serve`, on the other hand, *builds* the docs locally first and then serves those).
