### ISSUE TITLE
usage with mkdocs-multirepo

### ISSUE THREAD

**Issue by A-Baji** [jimporter/mike#109]
I am trying to create a [documentation hub](https://github.com/A-Baji/mk-docs-main) for various projects using [mkdocs-multirepo](https://github.com/wilhelmer/mkdocs-multirepo). I would like to implement mike versioning for the child docs, but not the parent. I have mike working in the [child repositories](https://github.com/A-Baji/mk-docs-sample1), but when accessing them through the parent hub it does not work since the multirepo tool creates submodules for the specified repositories, and then builds each's docs with vanilla mkdocs.

I'm wondering if there's any work around for this?

**Comment by jimporter** [comment]
If multirepo is driving the documentation build process, then it would need to add some configurability to be able to adjust the command to run for building each submodule. Specifically, this line would need to be updated: https://github.com/wilhelmer/mkdocs-multirepo/blob/d6390fea1ea4326ea392497e4454b48915a13134/mkdocs_multirepo/__init__.py#L70

Closing, as there's nothing mike can do about this (since it's not being invoked in the first place).

**Comment by A-Baji** [comment]
What command would need to be called instead on line 70 then? I could be wrong but I don't think mike has a standard `build` command. The only way to build is on deployment, which requires a version input.

There is also the issue that the submodules wont have access to past versions, as they don't exist in the source code, only in gh-pages, so even if I can build the submodules with mike, they wouldn't have any versions to select from.

**Comment by jimporter** [comment]
If that's what mkdocs-multirepo needs, then unfortunately the two tools just aren't compatible. mike 100% relies on being able to manage old versions of the generated docs in `gh-pages`.
