### ISSUE TITLE
0.6.0 was yanked from PyPi - is that expected?

### ISSUE THREAD

**Issue by heitorlessa** [jimporter/mike#114]
Hey Jim, was there any issue with the older 0.6.0 version in PyPi to be yanked?

Our build failed as the wheels are no longer found, so I suspect something went on but couldn't find any existing issues: https://pypi.org/project/mike/0.6.0/

Thanks a lot!

**Comment by jimporter** [comment]
Yes, that was intentional. I unpublished that release shortly after creating it, since it broke the Material theme at the time. (I had jumped the gun and removed the version selector hack in mike for Material too early. The Material theme had added built-in support for the version selector, but only for Insiders. Since I didn't want to break all non-Insiders, I rolled back to 0.5.5.)

However, the 0.6.0 artifacts are still on PyPI, and running `pip install mike==0.6.0` works just fine for me...

**Comment by heitorlessa** [comment]
Yeah, that's what I found odd when I hit this in GitHub Actions as it's been working for ages: https://github.com/awslabs/aws-lambda-powertools-python/runs/8274431228?check_suite_focus=true

I've bumped to 1.x as there doesn't seem to be any breaking changes affecting us. 

Thanks a lot Jim, closing.
