### ISSUE TITLE
Release an official version that supports GIT_COMMITTER_NAME/GIT_COMMITTER_EMAIL

### ISSUE THREAD

**Issue by d3xter666** [jimporter/mike#125]
Hi @jimporter,

This feature would make mike's git configuration a lot easier:  https://github.com/jimporter/mike/issues/98 / https://github.com/jimporter/mike/commit/2faa33ca4cf0da62c9c0ac7fbe8b60688733d7f1

Are you planning a more recent release that includes it?

We're trying to integrate `mike` into a Docker container and the GIT_COMMITTER_NAME/GIT_COMMITTER_EMAIL feature would help a lot, especially in a CI/CD environment.

Cheers

**Comment by jimporter** [comment]
Since the development version already has breaking changes, the next release will be version 2.0. That probably won't be for a while though, since I don't have a lot of time to work on this and there are still a few things that need done for the [2.0 milestone](https://github.com/jimporter/mike/milestone/1). I'd recommend just using the development version if it has features you need.
