### ISSUE TITLE
Proper docs?

### ISSUE THREAD

**Issue by Andre601** [jimporter/mike#135]
I feel like it would be good to have some proper documentation set up.
This would - ironically enough - also give an oportunity to show the per-version feature mike is offering.

I'm asking for this mainly because I wonder what command options mike has, what they do and if I actually do the setup correctly as currently my docs are not having any version selector using the material for mkdocs theme (Which supports Mike. And yes, I do have the extra setting enabled for it).
I do assume it's because I currently only have one "branch" in mike called dev, but I'm not sure...

Either way, some docs hosted on gh-pages could be good for A) Showing how it may look under specific theme(s), B) give a more IRL example of how it should be set up (Perhaps even with a gh actions example?) and C) show the feature in action by having the docs themself be build based on the version...

**Comment by jimporter** [comment]
> I feel like it would be good to have some proper documentation set up. This would - ironically enough - also give an oportunity to show the per-version feature mike is offering.

Sorry, but the README is the only documentation I plan on maintaining. There's really not that much to this project, so I don't think anything beyond a single file is worth the effort. As a way of showing off the results, the README links to a real-world project that uses mike, which should also provide some ideas for how to configure mike for your own purposes.

> I'm asking for this mainly because I wonder what command options mike has

These should all be summarized in the README, and any uncommon options that aren't described there should have details with `mike <subcommand> --help`.

> if I actually do the setup correctly as currently my docs are not having any version selector using the material for mkdocs theme (Which supports Mike. And yes, I do have the extra setting enabled for it). I do assume it's because I currently only have one "branch" in mike called dev, but I'm not sure...

You've probably misconfigured something, since the version selector should show up even with just a single version (unless the theme you've chosen is controlling that). If you file an issue with links to your repository and what you've tried, I can take a look though.

**Comment by Andre601** [comment]
Understandable. Tho, I feel like the README lacks a bit in terms of providing info.
While you can link to projects using it, is it also feeling a bit "lazy" (Cannot describe it better).
Like when I want to use something I want to check its docs then and there and not have to redirect myself to another project to see how it works. But that's just me.

Also, as a small side-note: For me does `mike <command> --help` not work strangely enough. It only gives me the main command info as output. `mike help <command>` on the other hand does work fine. Bit confusing but not to big of an issue.

**Comment by jimporter** [comment]
> While you can link to projects using it, is it also feeling a bit "lazy" (Cannot describe it better).

That's a good sign then. This project is extremely lazy! :) It really only exists to solve this problem for my own repositories because I'm too lazy to do this properly (that is, to set up a proper web server instead of storing release artifacts - docs - on a Git branch).

While I certainly don't mind people using the software I wrote, it's not my goal to try and *convince* others to use it. So I try to keep mike as simple as possible.

> Also, as a small side-note: For me does `mike <command> --help` not work strangely enough. It only gives me the main command info as output. `mike help <command>` on the other hand does work fine. Bit confusing but not to big of an issue.

That's odd. I checked both v1.1.2 and the latest dev version and `mike deploy --help`, etc all show exactly the same thing as `mike help deploy`.
