### ISSUE TITLE
Old Versions of Docs reapplied after delete

### ISSUE THREAD

**Issue by jeepMan79** [jimporter/mike#137]
Hi,

I'm sure I'm doing something wrong, but when I delete a version or all versions of the docs, they still come back after I rebuild....

1. mike delete --rebase --all -f -p

From CI
```yaml
   - git fetch origin $PAGES_BRANCH --depth=1 && git checkout -b $PAGES_BRANCH origin/$PAGES_BRANCH || echo "Pages branch not deployed yet."
    - git checkout $CI_COMMIT_SHA
    - mike deploy --prefix public -r $HTTPS_REMOTE -f -p -b $PAGES_BRANCH 8.1.0
    - mike set-default --prefix public -r $HTTPS_REMOTE -f -p -b $PAGES_BRANCH 8.1.0
    - git checkout $PAGES_BRANCH -- public/
```

Again, I'm probably doing something wrong :)

**Comment by jimporter** [comment]
Can you provide a link to the repository and the commits/CI jobs where this is occurring?

**Comment by jeepMan79** [comment]
It’s a private gitlab instance for work

**Comment by jimporter** [comment]
Unfortunately, it'll be pretty difficult for me to diagnose this without seeing the logs, but here are some things for you to take a look at:

1. I'm suspicious of your `mike delete` invocation; any time you're using `-f` (or `--rebase` for that matter), it's a sign that your local clone isn't up-to-date with upstream. Rather than adding those to make any errors go away, instead, make sure that the command works without them.
2. Related to the above, check the diff produced by `mike delete`; does the diff look right (i.e. are all the expected files actually deleted)?
3. In your commands, you're using `git fetch origin`, but `-r $HTTPS_REMOTE` later on; these should probably be the same.
