### ISSUE TITLE
Does Mike work when without GitHub? (self-hosting)

### ISSUE THREAD

**Issue by jgarte** [jimporter/mike#145]
Hi,

Does Mike work when without GitHub? (self-hosting)

**Comment by jimporter** [comment]
If you upload the contents of the `gh-pages` branch, you could do it, but I don't recommend it. See also #102.

**Comment by jgarte** [comment]
The issue is that I can't deploy my website to GitHub Pages.

**Comment by jimporter** [comment]
> The issue is that I can't deploy my website to GitHub Pages for the needs of the project I am working on.

You need to have a branch in your repository to hold your compiled documentation, since that's how mike keeps older versions around unchanged. However, you can use any branch you like for this; it doesn't *need* to be `gh-pages`.

> Is there an alternative MkDocs tool that you can recommend that is agnostic to using GitHub Pages as the deploy strategy?

No, but I really hope someone will write one. Ultimately, mike is just a hack. I wanted a system that treats compiled documentation as an immutable release artifact and which could use Github Pages as a host, since it's free. With access to a "real" web server, I think the better solution is to take advantage of its capabilities and get rid of all the `gh-pages` logic that mike uses. For example, you could probably just `rsync` the compiled docs to the right folder on the server, and then you'd just need a bit of logic for managing the `versions.json` file, which could probably be copied from mike's source code.

I haven't written something like that, but I expect it would be considerably simpler than mike, since mike needs to jump through quite a few hoops to work with Git.

**Comment by jimporter** [comment]
Another issue you can look at that summarizes this situation: #139.

**Comment by hellt** [comment]
@jimporter but what about having a command `mike build` that will build the versioned docs but will not attempt to commit to a remote?
This way we can have an intermediary step that allows users to take the generated artifacts (dir) and push it to any other server (Cloudflare pages, netlify, self hosted, etc)

**Comment by jimporter** [comment]
You don't have to involve a Git remote to use `mike`, just a Git branch (possibly local, if only one machine is managing the generated docs).

There's not really a way to do this differently though, short of rewriting the entire project. The `gh-pages` branch is where mike keeps track of all the *other* versions that should get deployed alongside the current one. That way, `HEAD` of the `gh-pages` branch is always the full site that should get deployed.
