### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by samuelcolvin** [jimporter/mike#154]
I'd like to use the  `alias_type` feature, which is only available on `main`.

**Comment by samuelcolvin** [comment]
btw, mike is great, thank you.

**Comment by jimporter** [comment]
When everything in the [2.0 milestone](https://github.com/jimporter/mike/milestone/1) is done, I'll tag a release (in particular, #106 is a hard blocker for the release). That'll probably take a while though, since I'm pretty busy and don't have a lot of free time to work on this project.

That said, I always try to keep master in a usable state, so there really shouldn't be any issues with using a dev build.

**Comment by samuelcolvin** [comment]
Sounds good, `master` is working  well for us.

By the way, [pydantic](https://github.com/pydantic/pydantic) has now fully adopted `mike`, including auto-deploy upon github release, and auto-deploy on push to `main`, with docs deployed to cloudflare pages - just in case you need an example to point people towards.

Thanks again for mike.

**Comment by jimporter** [comment]
Thanks, I'll take a look. It would probably be wise to add a few more real-world examples to the README (especially since the existing example I linked doesn't deploy via GH Actions),
