### ISSUE TITLE
Version drop-down missing from specific pages in main (unstable)

### ISSUE THREAD

**Issue by clubanderson** [jimporter/mike#171]
# Summary
We have a few versions on our mkdocs site served up by Mike now.  All pages in all versions show the dropdown at the top of the page.  For some reason, we have about 5 pages that do not show the dropdown.  These same pages, in the other versions, do show the dropdown.  We use some meta tags at the top of these 5 pages which could be causing the problem, but I am not sure how. One other note - I do see the dropdown appear for a split second, but then disappears like as if scrolling has started.  This only happens for our main branch.  All other versions are working fine.

# Configuration and Logs
compare this page https://docs.kubestellar.io/main/Coding%20Milestones/PoC2023q1/kubestellar-syncer/ (no dropdown) with this page https://docs.kubestellar.io/release-0.7/Coding%20Milestones/PoC2023q1/kubestellar-syncer/

our site is in source at - https://github.com/kubestellar/kubestellar/tree/main/docs

* Repository: https://github.com/kubestellar/kubestellar
* Platform: GitHub Actions
* `mike` version: 1.1.2
* Commit generated by `mike`: 
* CI configuration: https://github.com/clubanderson/kubestellar/actions/workflows/docs-gen-and-push.yml
* CI logs: 

# Steps to Reproduce
1. mike set-default latest
2. mike deploy --push --rebase --update-aliases main unstable
3. mike deploy --push --rebase --update-aliases release-0.7 stable
4. then observe the output as specified above

# Expected Behavior
I expected the dropdown to show on main branch as it does for all other branches of our documentation

# Additional Context

**Comment by jimporter** [comment]
This looks like a bug in the Material theme with the "topic" header (I'm not 100% sure what it's called since I don't use that theme). The version selector is still there in the DOM; it's just not being rendered properly.

You'll need to file a bug with the MkDocs Material developers, since (I'm pretty sure) there's nothing I can do about this. Of course, if it turns out there *is* a bug on the mike side of things, we can reopen this later.
