### ISSUE TITLE
Add support for "hidden" versions to the built-in theme extensions

### ISSUE THREAD

**Issue by jimporter** [jimporter/mike#187]
It should be possible to add a `hidden` property (see #138) to mark a version as hidden from the selector. This would mean it doesn't show up, except when it's the currently-selected version.

**Comment by jimporter** [comment]
@squidfunk Just wanted to give you a heads-up about this feature, in case you wanted to support it in your Material theme.

The short version is that users can now set arbitrary per-version properties, and one of them is `hidden`. That lets a user hide a specific version from the version selector (e.g. if they want to keep some old docs online, but not show them in the dropdown). [This commit](https://github.com/jimporter/mike/commit/367fbd009abfaa38a62aed6ecebb73f50d218e47) shows the new JS for the built-in themes to handle this.

**Comment by squidfunk** [comment]
Thanks for the heads up, sounds like a good addition! I'm currently busy on other parts of the project, but it is certainly an easy PR that can be done by somebody else, since we only need to filter by `hidden` in [`renderVersionSelector`](https://github.com/squidfunk/mkdocs-material/blob/1e313416e3fb4d5c8015a2bb42a50884c375c27c/src/templates/assets/javascripts/templates/version/index.tsx#L76-L92).

**Comment by reinaortega** [comment]
Currently using mike props --set hidden=true [version] that sets properly the hidden property, but there's no effect from the selector, all versions still appear on it.
