### ISSUE TITLE
Relative links with respect to versions

### ISSUE THREAD

**Issue by MaxHalford** [jimporter/mike#20]
Hi there. Before starting I just want to say that your library is great. It's definitely solving an important pain point. We're planning to use it for the next release of [creme](https://github.com/creme-ml/creme).

I just have a question with regards to links. In my MarkDown files, I have some links, such as `[LinearRegression](api-reference/linear_model/LinearRegression)`. When I click on the links, it redirects me to `localhost:8000/api-reference/linear-model/LinearRegression` instead of `localhost:8000/<insert_alias_or_version>/api-reference/linear-model/LinearRegression`. Is there anything specific I have to do in order to enable the desired behaviour?

I'm happy to clarify if my query is confusing.

**Comment by jimporter** [comment]
How are you running your test server? If you just run `mkdocs serve`, that'll only serve the un-versioned documentation as usual for vanilla MkDocs. To test out the versioning, you'll first need to use `mike deploy` to deploy a build of your docs to your `gh-pages` branch, and then run `mike serve` to serve the docs from the most-recent commit on the `gh-pages` branch.

If you're just testing things out and don't want to mess up your `gh-pages` branch, you can also specify `-b`/`--branch` to deploy to/serve from a different branch.

**Comment by MaxHalford** [comment]
I'm running the test server with `mike serve` after having called `mike deploy`. I've also tried deploying the docs remotely.

I believe I've got the grasp of `mike`, it's a really nice tool. I just can't figure out how to write relative links that work correctly with versioning.

**Comment by jimporter** [comment]
Hmm, it should Just Work. Maybe you're loading the non-`mike` version of the docs? If you go to `localhost:8000/api-reference/...`, that's probably your old docs from before you started using `mike`. To clean everything up, you can run `mike delete --all`, which will make a new commit on your `gh-pages` branch with all your old docs removed. Then you can run `mike deploy` and `mike serve` to test things out.

**Comment by JulioV** [comment]
I have the same problem, even after doing `mike delete --all` and deleting everything in `gh-pages` branch. You can see it in my [site](https://www.rapids.science/latest/), if you go to the bare domain it goes to `/latest/` as expected but if you click on `Installation` for example, it will go to /setup/installation/ instead of `/latest/setup/installation`. If you switch to `0.1` and click on `Installation` the same happens (goes to `rapids.science/setup/installation/`). I tried all this in a private browser session.

The steps I followed:

```bash
mike delete --all
git checkout gh-pages
rm -R *
git checout my-branch
mike deploy --push --update-aliases 0.1 latest
mike set-default --push latest
mike deploy --push --update-aliases 0.2 latest
```

**Comment by JulioV** [comment]
I think I figured out why this wasn't working. I was creating my links with a leading `/` so `[Installation](/setup/installation/)` has to be `[Installation](setup/installation/)`

Should this be in the docs? Happy to create a PR

**Comment by jimporter** [comment]
Hmm. I'm not sure if this needs to be called out specifically in the docs, since the issue of absolute paths also applies to vanilla MkDocs. If you're hosting on Github, your docs are usually somewhere like `https://foo.github.io/bar/...`, so an absolute path within your `bar` docs wouldn't work. It only works if you use a custom domain for your docs.

I'll think about it some more though. It might make sense to add a clearer "getting started" guide...

**Comment by MaxHalford** [comment]
Hey @jimporter, I think this issue can be closed.
