### ISSUE TITLE
Needs a demo

### ISSUE THREAD

**Issue by oprypin** [jimporter/mike#22]
Possibly the most important thing when evaluating a project is the ability to see how the result looks. I wasn't able to find that.
I think it would be really useful to have some placeholder docs with a few versions generated in all the supported themes.

**Comment by squidfunk** [comment]
I've added just placeholder docs for the new Material for MkDocs Insiders integration:
https://squidfunk.github.io/mkdocs-material-example-versioning/

**Comment by jimporter** [comment]
I can definitely link to some real-world example docs using this so people get a rough idea of what it looks like. I'm hesitant to make a full set of demos for all the themes since that requires a fair bit more wrangling of the files to get everything to work right, and this is one of those projects where I made it just because I really needed it for another project that's more interesting to me. :)

I'll think a bit more about it though, and maybe there's a simple way to get this all working without requiring too much extra work.

**Comment by jimporter** [comment]
(Partially) resolved in https://github.com/jimporter/mike/commit/fbb05bbd9f11c1fea2bec1621dce23640203aece
