### ISSUE TITLE
Add canonical links to docs

### ISSUE THREAD

**Issue by MrPowers** [jimporter/mike#235]
# Summary

I am setting the `canonical_version` to latest but the canonical link is not being generated in the HTML.

```
plugins:
  - mike:
      canonical_version: "latest"
```

# Configuration and Logs

* Repository: https://github.com/apache/sedona
* Platform: macos
* `mike` version: 2.1.3
* CI configuration: localhost development
* CI logs: no error, just not generating the canonical link

# Steps to Reproduce
1. Check out the branch with the mike changes: https://github.com/apache/sedona/pull/1735
2. Set the mike default: `mike set-default --push latest`
3. Generate the latest docs: `mike deploy latest`
4. Generate the 1.7.0 docs: `mike deploy 1.7.0`
5. Go to one of the 1.7.0 pages like `http://localhost:8000/1.7.0/api/sql/Constructor/`
6. Inspect the HTML and see there is no canonical link.  I expected to see `<link rel="canonical" href="http://localhost:8000/latest/api/sql/Constructor/" />`.

Thank you for the help and for building this awesome project!

**Comment by jimporter** [comment]
In order to have a canonical link in the HTML, you also need a [`site_url`](https://www.mkdocs.org/user-guide/configuration/#site_url) configured in your `mkdocs.yml`; it should be whatever the URL is for your docs *without* the version component. As noted in the linked documentation, vanilla MkDocs only sets the canonical link when `site_url` is configured.

**Comment by MrPowers** [comment]
@jimporter - that works, thank you!
