### ISSUE TITLE
CNAME inclusion

### ISSUE THREAD

**Issue by MaxHalford** [jimporter/mike#29]
Hey there,

Just wondering if the `CNAME` is supposed to be included out-of-the-box? Currently, the `CNAME` file is copied in each version directory, but it isn't included at the root of the directory. Please tell me if you want some more detail.

**Comment by jimporter** [comment]
In vanilla MkDocs, the way to include a `CNAME` file is different from how you'd do it with mike. With MkDocs, you'd put it in your `docs/` folder, since that becomes the root of your site. However, with mike, each version of your docs is in a subdirectory, so what you'd want to do is check out a copy of your `gh-pages` branch and just add the `CNAME` file to the root directory manually. The same process also applies for any other files you want that aren't version-specific.

This is probably worth adding some documentation for, since otherwise people will think the vanilla MkDocs documentation applies here, and it doesn't...

**Comment by MaxHalford** [comment]
Thanks, that's what I thought. I agree that a little entry in the documentation would help clarify. Cheers!
