### ISSUE TITLE
Compatibility with mkdocs-redirects

### ISSUE THREAD

**Issue by plannigan** [jimporter/mike#35]
[mkdocs-redirects](https://github.com/datarobot/mkdocs-redirects) allows for creating redirect pages when a page's path changes. If `example.com/foo/` is moved to `example.com/bar/`, the plugin generates an HTML page with a script that updates the `location.href` to cause the redirect (like `set-default`). However, since it is not aware that `mike` will place the generated content one directory down, the new `href` will be `/bar/` instead of `latest/bar/`.

`mkdocs-redirects` does check [site_url](https://www.mkdocs.org/user-guide/configuration/#site_url) in `mkdocs.yml` to see if the site is hosted in a sub-directory. This means `mike` could write out an updated `mkdocs.yml` with the version appended to the value of `site_url` to specify the name of the sub-directory.

**Comment by jimporter** [comment]
This seems like it would be easier to handle in mkdocs-redirects by taking advantage of relative paths. That would have the advantage of not requiring users to set `site_url` in general, and would probably fix https://github.com/datarobot/mkdocs-redirects/issues/17 as well.

There's probably some merit to updating `site_url` to point to the right location in general, but that's fairly painful to do since I wouldn't want to mess with the user's existing `mkdocs.yml` file (and a temporary `mkdocs.yml` would need to go in the same directory to keep relative paths working in the config).

**Comment by plannigan** [comment]
I think part of the complexity is that when the location is changed with a relative path, it is relative to the current location, not "root of the site". So when you are at `example.com/latest/foo/` and do `location.href = "bar/"`, you get sent to `example.com/latest/foo/bar/`.

I can look at it a bit from the `mkdocs-redirects` side too. It might have enough context information to produce the correct number of `..`'s to get back to the shared parent directory.

**Comment by jimporter** [comment]
> I can look at it a bit from the `mkdocs-redirects` side too. It might have enough context information to produce the correct number of `..`'s to get back to the shared parent directory.

Yeah, I *think* this should be the case. If you assume that `foo/bar` and `baz/quux` are siblings, it should just be a matter of counting how many path components are in the old path (2 in this case) and prefixing the new path with that many sets of `..`. There's probably some benefit to having `mkdocs-redirects` use absolute paths where possible, but if `site_url` isn't set, the only real option is relative paths, and that would also let it work cleanly with `mike`.
