### ISSUE TITLE
Can an alias ('latest') be a redirect instead?

### ISSUE THREAD

**Issue by oprypin** [jimporter/mike#40]
When creating a "latest" alias for some version, can I make it *redirect* to that version, rather than just being an exact copy?

Well, I'm pretty sure the answer is currently "no", so this is a feature request.

---

Check out how this site (non-MkDocs) works:

https://crystal-lang.org/api/latest/Hash.html
*redirects* you to
https://crystal-lang.org/api/0.36.1/Hash.html
*but* that page contains `<link rel="canonical" href="https://crystal-lang.org/api/latest/Hash.html">`.

I've been following this topic for some time and concluded that this is good for <abbr title="search engine optimization">SEO</abbr>. And also good for the users, since they don't end up sharing a `latest` link assuming it's permanent, when it's not.

---

Mike has aliases, and they work quite nicely.

You'd run `mike deploy 0.36.1 latest` and get both `/latest/Hash.html` and `/0.36.1/Hash.html` pages, and I see that both of them have the same `canonical` of `/0.36.1/Hash.html`, which is good.

In fact, I can run it in a slightly weird way, `mike deploy latest 0.36.1`, and then the canonical points to `/latest/Hash.html` on both pages, which is what I want.

The only aspect that I *don't* like is that, well, `/0.36.1/Hash.html` and `/latest/Hash.html`  are actual separate pages, rather than one redirecting to the other.

---

I could set up those redirects myself with some externally generated files, but would like to inquire about it as a feature first.

**Comment by jimporter** [comment]
Unfortunately, I don't think there's a good way to do this while continuing support for hosting on Github Pages.

As far as I know, the only way to specify a redirect on Github Pages is to make a skeleton HTML page for the source URL that has a redirect to the target URL. This isn't so bad when it's a single page (`user.github.io/project/index.html` => `[...]/latest/index.html`), but it's a lot harder when you want to redirect every page for a particular version. In theory, you could iterate over all the `*.html` files generated by MkDocs, but that's pretty complex, and I'd like to keep mike simple if at all possible.

If you know of a good way to specify richer redirects like with Apache for Github Pages, I'm all ears though. :) (Obviously, if you're deploying the results of `mike deploy` somewhere with access to a real server, you can set up redirects in a nicer way, but you'd have to set them up yourself, since mike doesn't know about `.htaccess` or anything like that.)

**Comment by oprypin** [comment]
> the only way to specify a redirect on Github Pages is to make a skeleton HTML page

Yes, and is that so bad? It's already generating the exact same number of pages for the /latest/ subdir, just with real content.

> you could iterate over all the *.html files generated by MkDocs, but that's pretty complex

Is it actually complex? My first hunch is that a plain glob `**/*.html` is enough. It's certainly doable with an external script too, just missing out on the integration with transparently adding stuff to gh-pages that *mike* handles so well.

> If you know of a good way to specify richer redirects like with Apache for Github Pages, I'm all ears though

I just ran across *slightly* better one for GitHub pages specifically.

https://github.com/crystal-lang/crystal-db/blob/a3b703e35f8926e9abb8edbf11168817d1905f1e/_config.yml
https://github.com/crystal-lang/crystal-db/blob/dfae44d5affa8a3d2a50b64202e3bd1ac460fe5d/api/latest/DB.md

**Comment by jimporter** [comment]
Hmm, looking at the existing code, it might actually be less work than I thought to use stub HTML files as redirects.

However, if mike does this on its own, the result will be that the canonical URL is the versioned URL (`/0.36.1/Hash.html`, not `/latest/Hash.html`), since the former is the "real" page that gets generated by MkDocs. I think this is somewhat important, since one of mike's goals is that docs are a build artifact just like binaries, so you shouldn't have to rebuild them post-release. Since the "latest" version changes over time, the only canonical URL that lasts forever is the versioned one.

That said, as of 1.0, if you want to change this behavior, you could just fork mike's MkDocs plugin and change this bit:
https://github.com/jimporter/mike/blob/7e7d34bfbeb30673b52ec56eb2e6d901f79a9e34/mike/mkdocs_plugin.py#L30-L33

**Comment by oprypin** [comment]
Thanks for the overall assessment.

> However, if mike does this on its own, the result will be that the canonical URL is the versioned URL (/0.36.1/Hash.html, not /latest/Hash.html)

That's also quite a good state of affairs :)

---

> you shouldn't have to rebuild them post-release

All the pages just retain `/latest/Hash.html` as canonical forever, you don't need to change anything (other than 'latest' itself, of course). Am I missing something?

Like, imagine I ran `mike deploy latest 0.36.1` and then `mike deploy latest 0.36.2` - I am not touching '0.36.1' but it'll still work fine (other than the complaints that the version already exists).

**Comment by jimporter** [comment]
Well, the issue is that `/0.36.1/Hash.html` would say its canonical URL is `/latest/Hash.html`, but the latter is actually for 0.36.2, which may have changed. This probably wouldn't matter for a point release, but for a major update, `Hash.html` might not even exist anymore (e.g. if the docs got restructured).

**Comment by oprypin** [comment]
OK yes that is true. First I thought that you misunderstood me, but you understand perfectly.

It's only in this particular setup that I mentioned that "redirect" and "canonical" point in the opposite directions. It's fine if you don't want to support that, it's just a weird SEO trick.
Sadly, something *needs* to be done about SEO, because otherwise search engines keep sending people to old versions, as those are the "popular" links.

For the record, Python does this too:

https://docs.python.org/3.9/reference/lexical_analysis.html
has the following `canonical`:
https://docs.python.org/3/reference/lexical_analysis.html
(not the other way around)

It wasn't always like this, but it's only when they started to do this that search engines stopped sending people to a random old version.

**Comment by jimporter** [comment]
Hmm, well if search engines are doing the wrong thing, I suppose I should at least add the *option* of changing the canonical URL. This will have to be manually set by the developer though, since mike doesn't know which alias is the "canonical" one (in the Python example, `3.9` might have aliases of `3` and `latest`).

**Comment by oprypin** [comment]
This works amazingly! Thanks much.

https://oprypin.github.io/crystal-db/latest/DB/Connection.html

**Comment by adriangb** [comment]
Just wanted to drop the detail here that symlinks work with GitHub pages. So you can symlink `latest` to another path on the branch.
