### ISSUE TITLE
Deploying to a subdirectory

### ISSUE THREAD

**Issue by oprypin** [jimporter/mike#42]
*Normally*, if I want to push a site to gh-pages under a /foo/ subdirectory, I could either literally put everything in that MkDocs site under such a subdirectory /docs/foo/, *or* I could use some deployment magic to just deploy directly to that subdirectory. Either way, it looks like: 
`https://username.github.io/reponame/foo/bar.html`

With *mike*, however, there's no deployment "magic", so I can't achieve
`https://username.github.io/reponame/foo/1.2.3/bar.html`
(unless I move the subdirectory manually every time after deployment)

I can only at best have this (via the MkDocs approach):
`https://username.github.io/reponame/1.2.3/foo/bar.html`
but it's not a good solution for the site I'm currently migrating, so I am asking for the ability to do the former.

Sorry about another feature request. Seems like it's the last one.

**Comment by jimporter** [comment]
That makes sense. It's probably not a super-common thing people would want to do, so I think it should be sufficient to provide a `--prefix` option for the various commands. It does require the person deploying the docs to remember that flag, but I'd guess that most projects whose docs are complex enough to need this would already be using an automated process to build their docs, so there won't be a lot of manual interaction with mike.

**Comment by oprypin** [comment]
@jimporter I'm trying out your commit b24149e271255e31c9e1b1595cd3a350876a7d7c here
* [Code](https://github.com/crystal-lang/crystal-db/commit/416eef23b2d99d86b89c07894aa45404f97b987f#diff-87e860af4b9db6c503ed680b6edb6333c6f8d7659f7d1a779a2487466bbc50f6R28)
* [Site](https://oprypin.github.io/crystal-db/api/0.10.0/)

and it works great but I found one issue.

Clicking the site logo in the top left corner brings you to /latest, not /prefix/latest.

**Comment by jimporter** [comment]
That's because of [this line](https://github.com/crystal-lang/crystal-db/blob/416eef23b2d99d86b89c07894aa45404f97b987f/mkdocs.yml#L2): 

```yml
site_url: https://oprypin.github.io/crystal-db/
```

The `site_url` would need to include the prefix for it to work right. I'm of two minds about this: on the one hand, mike already fixes up the `site_url` to account for the version number so maybe it should account for `--prefix`. On the other hand people might want to add a prefix for compatibility with some other step in their deployment process, so maybe mike shouldn't try to guess how the final result will be structured.

**Comment by oprypin** [comment]
Oh I'm sorry, you're totally right
