### ISSUE TITLE
Feature request: Update an existing version

### ISSUE THREAD

**Issue by heitorlessa** [jimporter/mike#48]
Hello and thank you for creating this neat utility!

 Is there a way to update an existing version deployed with Mike? If not, is that in the future plans?

  **Use case**: I'd like to keep an `unreleased/develop` version where mike would update such existing version upon merge requests. Another example is quickly fixing typos or any trivial content in the docs after it's already live. While I can delete and re-create the same version it can cause disruption.

I'd be happy to contribute after understanding the contribution guidelines and [codebase](https://github.com/jimporter/mike/blob/0cad14002a7bd94268e0bf042bbbe20f672339e4/mike/versions.py#L22).

Thank you!

**Comment by jimporter** [comment]
All you need to do here is deploy to the same version number. If that version has any aliases associated with it, those aliases will also be updated automatically. This could probably stand to be documented more explicitly, since I think it's only mentioned in passing.

**Comment by heitorlessa** [comment]
Thanks @jimporter - when I first tried that I received the "duplicated version" message.

I'll try that again as I suspect looking at the code it's the combination of version and alias that triggers the error.

**Comment by jimporter** [comment]
You know, I should have looked at the link you included in the original report; I totally missed it!

If you're hitting that error it's because you're doing something like this:

```
mike deploy 1.0 1.0
```

That sets the version to be `1.0` and also adds an *alias* of `1.0`. That's not allowed, since a version and an alias are both represented as subdirectories in your generated docs, so they'd conflict. In this case, just run, `mike deploy 1.0`.

**Comment by heitorlessa** [comment]
I've just tested and works as expected :) Looking at the history, I had tried both and quite possibly confused myself with the many versions and alias combinations I was experimenting with.

Thanks a lot!
