### ISSUE TITLE
GitHub Action example

### ISSUE THREAD

**Issue by jwillmer** [jimporter/mike#79]
I try to setup `mkdocs` with `mike` (versions) with GitHub actions but do not find any examples - it's the first time I play around with mkdocs. Can anyone provide one so I don't need to spend time on figuring it out by my self? Maybe we should add it into the documentation of `mike`?

**Comment by jimporter** [comment]
I don't think there's a one-size-fits-most solution here, since no example can really explain how your CI will determine the version to deploy. Once you've solved that though, it's mostly a matter of running `mike deploy VERSION --push`.

There are some subtleties with checking out the `gh-pages` branch and setting up a user (as documented [here](https://github.com/jimporter/mike#deploying-via-ci)), but those are really just general things that apply to *any* Github Action. I'm not sure there's much more I could add beyond taking the linked section about deploying to CI and just gluing it together into a single snippet...

**Comment by jwillmer** [comment]
I already fixed it myself. For future reference anyone who sees this issue can look at https://github.com/RemoteCloud/public-documentation for some example.
