### ISSUE TITLE
Versioning not showing on page

### ISSUE THREAD

**Issue by tvdboom** [jimporter/mike#93]
Hi,

I have a documentation website build with mkdocs-material. 

Link to repo: [https://github.com/tvdboom/ATOM](https://github.com/tvdboom/ATOM)
Link to docs: [https://tvdboom.github.io/ATOM/](https://tvdboom.github.io/ATOM/)

I followed mike's documentation step by step and published using mike.
When I run `mike list` on my terminal I get:

4.12 [latest]
4.11
4.10
4.9
4.8
4.7
4.6
4.5
4.4
4.3
4.2
4.1
4.0

When I run `mike serve`  the expected website **with** versioning runs locally, but when I push to master, GitHub still uses the website **without** versioning.

Also, the gh-pages branch on the repo is updated with all versions. Still, the github pages is loading without mike since the URL is still the old one, without the /version/. It seems that github is not "aware" of the mike pages.

Any ideas why this is happening? Thanks in advance

**Comment by kenji-miyake** [comment]
(Note that I'm not a maintainer but just a user.)

@tvdboom I think it's because you are deploying the `master` branch.
https://github.com/tvdboom/ATOM/tree/master/docs

I believe it will work if you specify `gh-pages` here.
![image](https://user-images.githubusercontent.com/31987104/155735146-30b6f2cb-75df-4cc2-b1ef-b3717413a8a2.png)

**Comment by tvdboom** [comment]
That was the problem indeed. Thanks a lot!
